# Generated by Django 3.2.7 on 2021-11-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20211126_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Certificate_image', models.ImageField(null=True, upload_to='pics')),
                ('Certificate_title', models.TextField(null=True)),
                ('Certificate_description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coding_skils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.TextField(null=True)),
                ('skills_per', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education_experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_name', models.TextField(null=True)),
                ('E_year', models.IntegerField(null=True)),
                ('E_course', models.TextField(null=True)),
                ('E_acquired', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fetured_Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_image', models.ImageField(null=True, upload_to='pics')),
                ('F_name', models.TextField(null=True)),
                ('F_year', models.IntegerField(null=True)),
                ('F_tech', models.TextField(null=True)),
                ('F_description', models.TextField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='home',
            old_name='C_description',
            new_name='Intro_descrption',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='C_title',
            new_name='Intro_hi',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='C_image',
            new_name='Intro_img',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='E_acquired',
            new_name='Intro_per',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='I_resume',
            new_name='Intro_resume',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='E_course',
            new_name='Intro_skills',
        ),
        migrations.RemoveField(
            model_name='home',
            name='E_name',
        ),
        migrations.RemoveField(
            model_name='home',
            name='E_year',
        ),
        migrations.RemoveField(
            model_name='home',
            name='F_description',
        ),
        migrations.RemoveField(
            model_name='home',
            name='F_image',
        ),
        migrations.RemoveField(
            model_name='home',
            name='F_name',
        ),
        migrations.RemoveField(
            model_name='home',
            name='F_tech',
        ),
        migrations.RemoveField(
            model_name='home',
            name='F_year',
        ),
        migrations.RemoveField(
            model_name='home',
            name='I_descrption',
        ),
        migrations.RemoveField(
            model_name='home',
            name='I_hi',
        ),
        migrations.RemoveField(
            model_name='home',
            name='I_img',
        ),
        migrations.RemoveField(
            model_name='home',
            name='I_per',
        ),
        migrations.RemoveField(
            model_name='home',
            name='I_skills',
        ),
        migrations.RemoveField(
            model_name='home',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='home',
            name='skills_per',
        ),
    ]
