# Generated by Django 3.2.7 on 2021-11-26 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20211126_1249'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='home',
            new_name='Intro',
        ),
    ]
