# Generated by Django 3.2.7 on 2021-11-26 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_home_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intro',
            name='Intro_per',
        ),
        migrations.RemoveField(
            model_name='intro',
            name='Intro_skills',
        ),
    ]
