# Generated by Django 3.2.7 on 2021-11-26 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_certificate_certificate_yes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='Certificate_yes',
        ),
    ]
